/*
 * This source file was generated by the Gradle 'init' task
 */
package eu.stcatherines.kotlin

import kotlin.test.Test
import kotlin.test.assertEquals

class AppTest {
    @Test
    fun appHasAGreeting() {
        assertEquals(
            "Hello, World!",
            helloWorld()
        )
    }
}
